name: 'Bug report 👾'
description: 'Create a report to help us improve'
title: '[BUG] '
labels:
  - bug
body:
  - type: textarea
    id: bug-description
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is.'
      placeholder: 'I was trying to [...] but [...]'
    validations:
      required: true

  - type: textarea
    id: bug-reproduction-steps
    attributes:
      label: 'To Reproduce'
      description: 'Steps to reproduce the behavior:'
      placeholder: '1. Go to [...]'
    validations:
      required: true

  - type: textarea
    id: bug-expected-behavior
    attributes:
      label: 'Expected behavior'
      description: 'A clear and concise description of what you expected to happen.'
      placeholder: 'I expected [...]'
    validations:
      required: true

  - type: textarea
    id: bug-screenshots
    attributes:
      label: 'Screenshots'
      description: 'If applicable, add screenshots to help explain your problem.'
      placeholder: 'Add screenshots here'

  - type: textarea
    id: bug-additional-info
    attributes:
      label: 'Additional context'
      description: 'Add any other context about the problem here.'
      placeholder: 'I am using [...]'
